version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - GIT_TAG=${GIT_TAG:-$(echo $CODEBUILD_WEBHOOK_TRIGGER | awk -F/ {'print $2'})}
      - aws s3 rm s3://$DEPLOYMENT_BUCKET/ --recursive --exclude "404.html" --exclude "index.html" --exclude "sitemap.xml"
      - aws s3 cp s3://$BUILD_BUCKET_ARTIFACTS/$GIT_TAG s3://$DEPLOYMENT_BUCKET --recursive
      - sed -e "s|%CODEBUILD_WEBHOOK_TRIGGER%|$CODEBUILD_WEBHOOK_TRIGGER|" cache-invalidation.json.tpl > cache-invalidation.json
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --invalidation-batch file://cache-invalidation.json
    finally:
      - bin/discord.sh
